### ISSUE TITLE
Keypress issues

### ISSUE THREAD

**Issue by vialde** [dsanchezseco/punk75#4]
Morning,

Just wanted to say how happy I am that you've open sourced this design...I really like it.  I've got a quick question.  I'm having issues with my build.  I've had the PCBs fab'd and soldered on all the components.  Flashed the firmware using the instructions in your other repo....everything looked good.  Unfortunately it's not registering keypresses.  I'm new to the Keyboard pcb game...I've done a few hand wired boards using pro micros, but I'm not sure what to troubleshoot here.  Both led's light up when the usb cable is plugged in...that's the only response I get.  Any thoughts or tips?  
Cheers

**Comment by dsanchezseco** [comment]
Hi! glad you like it and honored you build it! 

The other repo is the bootloader, the only thing I can think of is that you might be missing the actual keymap.

it would be a regular QMK flash process now that you have the bootloader. One of the leds should blink when a keypress is registered. If I remember correctly with the bootloader only it just turned on to tell you the bootloader is correctly in.

It's being a while since I created and I barely remember the process 😅

**Comment by vialde** [comment]
Hey, that might be the issue.  I thought the bootloader contained everything.  okay.  so the question is now...can I flash via the usb c or do I need to used the adapter again?

**Comment by dsanchezseco** [comment]
USB-C just hold the boot button, plug it in or press reset, hold the boot a couple seconds more and the you are good to do the flash with QMK

-------- Original Message --------

**Comment by vialde** [comment]
Ahhh, okay.  I just managed to get it working with the adapter!  Keypresses are registering now!  Thanks for putting this all out there for people to use.  I love the design and the build instructions were spot on.  Now to solder on some switches.

Cheers!

**Comment by dsanchezseco** [comment]
Is it working then?? Enjoy it!! I loved making and using it, i hope you do as well!

-------- Original Message --------

**Comment by vialde** [comment]
![PXL_20230501_104247621 MP (1)](https://user-images.githubusercontent.com/768156/235477555-eb08619b-3c3c-4602-aff4-c1154d1c9f4a.jpg)
Working like a charm!  Now for a case!
